### ISSUE TITLE
Header is not properly visible in mobile

### ISSUE THREAD

**Issue by lmas3009** [MCPI-Revival/mcpi-revival.github.io#22]
Can i work on this to make it responsive on a mobile phone?
Can you pls assign me to complete it.

**Comment by Alvarito050506** [comment]
Hello! Thanks for your interest, we're currently slowly working on a redesign at the `alv-wip` branch (there's also `Website-rewrite`, but that one has been deprecated), which should improve responsiveness. Contributions are welcome, so if you want to work on it, just fork the project and start making PRs... If you have any doubts or more specific questions, I would recommend joining the [Discord](https://discord.com/invite/QGsZakfx), where we talk and discuss most projects.
